### ISSUE TITLE
Using redis in sentinel mode?

### ISSUE THREAD

**Issue by danielloader** [caddyserver/cache-handler#100]
Hello all!

I've successfully got this cache working with a single pod deployment of redis, but I've yet to have any luck with getting this to work with a sentinel deployment. 

Has anyone succeeded with this and if so, could you share your configuration?

As a follow up question, what's the difference between redis and redis-go in this module?

**Comment by darkweak** [comment]
Hello @danielloader thank you for your interest about the cache-handler.
Using `go-redis` you should be able to use the following configuration:
```
{
    cache {
        redis {
            Addrs redis1:6379 redis2:6379 redis3:6379 redis4:6379
            MasterName my-master
        }
    }
}

localhost {
    route {
        cache
    }
}
```

And using `rueidis` (the client used in the `redis` storage):
```
{
    cache {
        redis {
            InitAddress redis1:6379 redis2:6379 redis3:6379 redis4:6379
            Sentinel {
                MasterSet my-master
            }
        }
    }
}

localhost {
    route {
        cache
    }
}
```

The differences between the `redis` and `go-redis` storages are the client used behind. Rueidis consumes more bandwidth than Go-redis but is more than Go-redis (better performances but more consumptions so that depends on your needs).

**Comment by danielloader** [comment]
Thanks, perfect.
