### ISSUE TITLE
Possible to configure a disk based cache instead of in-memory?

### ISSUE THREAD

**Issue by carterbryden** [caddyserver/cache-handler#21]
I'm not sure if this is something that badger or olric can do, but I'm looking to cache pages to disk using the cache handler and then serve them from there, rather than keeping it in memory for the ttl.

Is this something that this plugin can do? If so, are there any docs or examples for this? I followed the link to the official badger docs, but I didn't see anything for this specifically.

Thank you!

**Comment by darkweak** [comment]
Hello @carterbryden You can use the `badger.path` configuration property to set a file to cache on disk. It's a hack but it works.  
To explain how it works under the hood. It creates a badger DB instance from the default options and merge the options in declared the configuration (your caddyfile or caddyfile.json).

I'll write an example of this declaration asap.

**Comment by ueffel** [comment]
I just played around with the badger configuration. It seems that configuration I provide via Caddyfile isn't used.
Example:

```caddy-d
{
	order cache before rewrite
	cache {
		badger {
			path cache.json
			configuration {
				ValueLogFileSize 16777216
				MemTableSize 4194304
				ValueThreshold 524288
			}
		}
	}
}
```

It outputs `Impossible to parse the configuration for the default provider (Badger)`. 
The problem seems to be that configuration value are all read as string, so the unmarshalling to the badger configuration struct errors out with `json: cannot unmarshal string into Go struct field Options.MemTableSize of type int64`

Is there any way to provide the correct configuration via Caddyfile or is that only possible via json config?

**Comment by francislavoie** [comment]
Sounds like a bug. The Caddyfile unmarshaling should convert those values to numbers before inserting them in the config to be exported. Even better if it uses `github.com/dustin/go-humanize` as Caddy already does, to allow values like `4MB` to be configured which would be converted into the amount of bytes, etc.

**Comment by darkweak** [comment]
https://github.com/darkweak/souin/pull/189/commits/2b9ed48e3e1cf2cf86c8bf4b28d54b7f3595542e should fix your issue @ueffel

**Comment by darkweak** [comment]
@ueffel we would know if the latest release of Souin solve your issue with the low-level badger configuration. Can you try with the darkweak/souin/plugins/caddy@latest dependency please?

**Comment by ueffel** [comment]
@darkweak 
Configuration via Caddyfile works

**But** I have a complaints about it: 
* i'm getting `Impossible to open the Badger DB. Cannot create lock file "[<badger.path>\\LOCK]()".  Another process is using this Badger database error:`
* It is possible to misconfigure badger so `badger.Open` returns an error (<https://github.com/darkweak/souin/blob/master/cache/providers/badgerProvider.go#L41-L45>)
  In that case caddy should not start and report the error, otherwise requests, that try to use the cache, are not getting any response. (The output to stdout is not good enough I'm afraid.)

  Example misconfiguration:
  
  ```caddy-d
  {
  	order cache before rewrite
  	cache {
  		badger {
  			path cache.json
  			configuration {
  				ValueLogFileSize 16777216
  				MemTableSize 4194304
  				# ValueThreshold 524288
  			}
  		}
  	}
  }
  ```
* values like `16MiB` for size related configurations (like @francislavoie suggested) are not supported and also it does not even report an error

**Comment by darkweak** [comment]
You have to set the BypassLockGuard property in the badger configuration to bypass that.

**Comment by darkweak** [comment]
Every cache directives open the badger database. You can override the path in each directive to have a single access per directive but I'm working on a singleton implementation to support this use case.
