### ISSUE TITLE
how to configure redis with caddy?

### ISSUE THREAD

**Issue by vncloudsco** [caddyserver/cache-handler#40]
hello team
I have read the configuration but still don't understand how to configure because the documentation is not clear when configuring caddy with redis, i have configured redis on Caddyfile  as below but found that they don't work with cache, so how can i configure it properly?  Can someone give me a sample Caddyfile configuration file?

```
{
        order coraza_waf first
        order cache before rewrite
}
caddy.manhtuong.net {
        coraza_waf {
                include /etc/caddy/waf/config.conf
                include /etc/caddy/waf/whitelist.conf
                include /etc/caddy/waf/coreruleset/crs-setup.conf.example
                include /etc/caddy/waf/coreruleset/rules/*.conf
        }
        cache {
                redis {
                        url 127.0.0.1:6789
                }
        }
        route / {
                rate_limit {body.id} 200r/m
        }
        file_server {
	        hide .git
        }
        reverse_proxy x.x.x.x:9000
        log {
                output file /home/caddy/caddy.manhtuong.net.log
        }
}
```

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! So far, this doesn't look like a bug in Caddy. It looks more like a question about how to use Caddy rather than a bug report or feature request.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!

**Comment by PythonLinks** [comment]
I will chime in here.  I also have problems with configuration, so I am now unhappily using nginx.  You recently released a new version, with a very simple configuration example, but more work on the docs, and more simple examples are  most needed. 

Someday you will get it right, and then I will be able to ditch NGINX and certbot and all of that complexity.

**Comment by darkweak** [comment]
> more work on the docs

@PythonLinks You can submit a PR for that if you think that the configuration is not clear. Ask for specific configurations examples with the cases you want to know how to configure. 🙂

**Comment by darkweak** [comment]
@vncloudsco there was a wrong condition in the redis provider integration. Resolved here https://github.com/darkweak/souin/issues/270#issuecomment-1293873241 but not yet available in the cache-handler (I plan to create the release on monday 🤞).

**Comment by vncloudsco** [comment]
@darkweak this is good news thank you! I will wait for information from you!

**Comment by darkweak** [comment]
@vncloudsco sorry for the delay, I prepared the PR to bump the Souin dependency and I had to check if everything works well using the latest release. I will merge and tag the new version tomorrow.

**Comment by darkweak** [comment]
@vncloudsco v0.4.0 has been released! Feel free to reopen if needed.
